### ISSUE TITLE
Feature Request - Folia

### ISSUE THREAD

**Issue by roggy666** [goldeneas/CustomTabCompleter#5]
Hello! This plugin is really nice, but I want to ask, can you add Folia support?

**Comment by goldeneas** [comment]
Folia's documentation is not currently working, therefore I am not able to provide support for Folia. As soon as it comes back, I will try adding support for multithreading.

**Comment by goldeneas** [comment]
After some more insight, I will not be adding support for Folia. It's a server software that hasn't been even officially released yet, is bound to changes and (supposedly) breaks compatibility with every minecraft plugin.
I might work on this when Folia will be released, and also when there is going be good development documentations.
